apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    {{- range .Values.service }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
      port: {{ .port }}
      nodePort: {{ .nodePort }}
    {{- end }}
  selector:
    app: {{ .Values.name }}
