########################################################################################
# # docker
# 
# docker images # show all images
# sudo docker stop $(sudo docker ps -a -q)
# sudo docker rm $(sudo docker ps -a -q)
# 
# # configuration path: drive/container/
# docker compose -f /path/to/heimdall.yml up -d
# docker compose -f /path/to/heimdall.yml down
#
# # docker networking
# sudo docker network ls
# docker inspect wgnet
#
# interative bash
# docker exec -it <mycontainer> bash
# check logs
# sudo docker logs <mycontainer>
#
# sudo docker run --network=ssserver_default --network-alias=wireguard -ti --rm ubuntu /bin/bash
########################################################################################
---
name: ssserver
version: "3.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
        #       - SERVERURL=wireguard.domain.com #optional
        #       - SERVERPORT=51820 #optional
        #       - PEERS=1 #optional
        #       - PEERDNS=auto #optional
        #       - INTERNAL_SUBNET=10.13.13.0 #optional
        #       - ALLOWEDIPS=0.0.0.0/0 #optional
        #       - PERSISTENTKEEPALIVE_PEERS= #optional
        #       - LOG_CONFS=true #optional
    volumes:
      - /home/coupe/drive/container/wireguard_config:/config
      - /lib/modules:/lib/modules #optional
        #     networks:
        #       wireguard-net:
        #         ipv4_address: 172.20.0.50
    ports:
      - 9091:9091
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    depends_on:
      - wireguard
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/coupe/drive/container/transmission_config:/config
      - /home/coupe/drive/downloads:/downloads
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/coupe/drive/container/jellyfin_config:/config
      - /home/coupe/drive/downloads:/data/media
    ports:
      - 8096:8096
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/coupe/drive/container/homeassistant_config:/config
    ports:
      - 8123:8123 #optional
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
    volumes:
      - /home/coupe/drive/container/mariadb_config:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/coupe/drive/container/nextcloud_config:/config
      - /home/coupe/drive/nextcloud:/data
    ports:
      - 443:443
    restart: unless-stopped

  jupyterlab:
    image: jupyterlab:latest
    container_name: jupyterlab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/coupe/drive/jupyter:/home/jupyter
    ports:
      - 8888:8888
    restart: unless-stopped

networks:
  wireguard-net:
    driver: bridge
    name: wgnet
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

---
# wordpress server
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Etc/UTC
      - MYSQL_DATABASE=WP_database
      - MYSQL_USER=WP_dbuser
      - MYSQL_PASSWORD=WP_dbpassword
    volumes:
      - /home/ubuntu/docker/mariadb:/config
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=stevenwang.trade
      - SUBDOMAINS=
      - VALIDATION=http
    volumes:
      - /home/ubuntu/docker/swag:/config
    ports:
      - 443:443
      - 80:80
    depends_on:
      - mariadb
    restart: unless-stopped
