# desired state

apiVersion: apps/v1       # required
kind: Deployment          # required
metadata:                 # required
  name: nginx-deployment
  namespace: nginx-namespace
spec:                     # required
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
