#!/bin/bash
touch speed
max=0
temp=0
for i in `seq 1 3600`; do
	temp=$(transmission-remote -l | grep Sum | tr -s ' ' | cut -d ' ' -f 5);
	if [[ $temp > $max ]]; then
		max=$temp
		echo "$max"	>> speed
	fi
	i=i+1
	sleep 1s
done
