apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: {{ .Values.namespace}}
spec:
  volumeMode: Filesystem
  storageClassName: nfs
  selector:                                                                             
    matchLabels:                                                                        
      type: clustervault
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Gi # this is used when looking for PVbest way to use a single nfs share for all the deployment in a cluster with enough storage, when the clain happens, the pod always claim the entire storage capacity of the PV
