apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: lscr.io/linuxserver/code-server:4.16.0
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        volumeMounts:
          - name: my-nfs-storage
            mountPath: /config
            subPath: code-server
        ports:
        - containerPort: 8443
      volumes:
        - name: my-nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: homelab
spec:
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 8443
      nodePort: 30000
  type: NodePort
