# vscode setting: /config/data/User/settings.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      # nodeSelector:
      #   type: x86_p
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       preference:
      #         matchExpressions:
      #         - key: type # label name
      #           operator: In
      #           values:
      #           - x86_p
      #     - weight: 50
      #       preference:
      #         matchExpressions:
      #         - key: type
      #           operator: In
      #           values:
      #           - x86_e
      #     - weight: 10
      #       preference:
      #         matchExpressions:
      #         - key: type
      #           operator: In
      #           values:
      #           - arm64
      containers:
      - name: code-server
        # image: lscr.io/linuxserver/code-server:latest
        # image: 192.168.8.9:5000/code-server-s:latest
        # imagePullPolicy: Never
        image: 192.168.8.8:5000/code-server:20240616
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        - name: PASSWORD
          value: "gaza"
        - name: SUDO_PASSWORD_HASH
          value: $6$cyber$/8YWLe2rdjv1T0.SlAUYOygBavRRZFj3YPnIZgtOTUBMMa5RUqYcNw2enBty8krqiQ3CxeFn8mreiSjkzvr39.
        volumeMounts:
          - name: my-nfs-storage
            mountPath: /config
            subPath: code-server
        ports:
        - containerPort: 8443
      volumes:
        - name: my-nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: homelab
spec:
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 8443
      nodePort: 8443
  type: NodePort
    # ---
    # apiVersion: networking.k8s.io/v1
    # kind: Ingress
    # metadata:
    #   name: code-server
    #   namespace: homelab
    # spec:
    #   rules:
    #   - host: aionk.duckdns.org
    #     http: # note this is the 2nd step of direct traffic to internal service, not to confuse with the 1st step of https that you put in your browser
    #       paths:
    #       - path: /code-server
    #         pathType: Prefix
    #         backend:  # internal target
    #           service:
    #             name: code-server
    #             port:
    #               number: 8443
    #   tls:
    #   - hosts:
    #     - aionk.duckdns.org
    #     secretName: example-local-tls

