apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-nfs-pvc
  namespace: homelab
spec:
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti

