apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: rootu
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: rootp
        volumeMounts:
          - name: nfs-storage
            mountPath: /data
            subPath: mongodb
        ports:
        - containerPort: 27017
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: homelab
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      nodePort: 30017
  type: NodePort
