# make sure to set up DNS record on the DNS provider side properly
# get DNS server token and set in the dns config
# update nginx proxy conf

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swag
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swag
  template:
    metadata:
      labels:
        app: swag
    spec:
      containers:
      - name: swag
        image: lscr.io/linuxserver/swag:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: homelab-cm
              key: domain
        - name: SUBDOMAINS
          value: "wildcard"
        - name: VALIDATION
          value: "dns"
        - name: DNSPLUGIN
          value: "google-domains"
        volumeMounts:
          - name: my-nfs-storage
            mountPath: /config
            subPath: swag
        ports:
        - containerPort: 443
        - containerPort: 80
      volumes:
        - name: my-nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: swag
  namespace: homelab
spec:
  selector:
    app: swag
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      targetPort: 443
      port: 443
      nodePort: 30443
  type: NodePort
