apiVersion: apps/v1
kind: Deployment
metadata:
  name: swag
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swag
  template:
    metadata:
      labels:
        app: swag
    spec:
      containers:
      - name: swag
        image: lscr.io/linuxserver/swag:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: URL
          value: mantide.ddns.net
        - name: VALIDATION
          value: "http"
        volumeMounts:
          - name: my-nfs-storage
            mountPath: /config
            subPath: swag
        ports:
        - containerPort: 443
      volumes:
        - name: my-nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: swag
  namespace: homelab
spec:
  selector:
    app: swag
  ports:
    - protocol: TCP
      port: 443
      nodePort: 30443
  type: NodePort
