apiVersion: v2
name: influxdb
version: 0.1.0  # A SemVer 2 version (required)
  # kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: A simple influxdb deployment
# A chart can be either an 'application' or a 'library' chart.
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
keywords:
  - influxdb
  - nosql
    # home: The URL of this projects home page (optional)
    # sources:
    #   - A list of URLs to source code for this project (optional)
    # dependencies: # A list of the chart requirements (optional)
    #   - name: The name of the chart (nginx)
    #     version: The version of the chart ("1.2.3")
    #     repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
    #     condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
    #     tags: # (optional)
    #       - Tags can be used to group charts for enabling/disabling together
    #     import-values: # (optional)
    #       - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    #     alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
maintainers: # (optional)
  - name: Steven
    email: steven@s.com
    url: stevenwang.trade
icon: A URL to an SVG or PNG image to be used as an icon (optional).
  # appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
deprecated: false
  # annotations:
  #   example: A list of annotations keyed by name (optional).

