apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /home/coupe/drive/clustervault
    server: 192.168.50.64
