---
dnsmasq:
  customDnsEntries:
    - address=/kk.com/192.168.8.8
 
  customCnameEntries:
    - cname=foo.kk.com,kk.com

serviceWeb:
  # loadBalancerIP: 192.168.8.9
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: pihole-svc
  # type: LoadBalancer
  type: NodePort
  http:
    port: 888
    nodePort: "888"

serviceDns:
  # loadBalancerIP: 192.168.8.9
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: pihole-svc
  # type: LoadBalancer
  mixedService: true
  type: NodePort
  port: 5353
  nodePort: 53

persistentVolumeClaim:
  enabled: true
  existingClaim: nfs-pvc
  subPath: pihole

    # resources:
    #   limits:
    #     cpu: 400m
    #     memory: 512Mi
    #   requests:
    #     cpu: 200m
    #     memory: 256Mi
adminPassword: admin

