# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: nginx-proxy-manager
# For helm, it's best not to hardcode namespace in the deployment.yaml
namespace: homelab

replicaCount: 1

image:
  repository: jc21/nginx-proxy-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
    # - name: TZ
    #   value: "America/New_York"

volumes:
  - name: nfs-storage
    claimName: nfs-pvc
    mountPath: "/data"
    subPath: "nginx-proxy-manager-data"
  - name: nfs-storage
    claimName: nfs-pvc
    mountPath: "/etc/letsencrypt"
    subPath: "nginx-proxy-manager-letsencrypt"

service:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 180 # tried 80, doesn't work, not sure if 180 works
    nodePort: 80
  - name: https
    protocol: TCP
    targetPort: 443
    port: 1443 # tried 443, doesn't work, not sure if 1443 works
    nodePort: 443
  - name: ui
    protocol: TCP
    targetPort: 81
    port: 81
    nodePort: 81
