apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-transmission-downloads-nfs-pv
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /home/coupe/drive/downloads
    server: 192.168.50.64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-nfs-pvc
  namespace: wireguard-transmission
spec:
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti

