apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-transmission-nfs-pv
  labels:
    type: transmission-nfs
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /home/coupe/drive/clustervault
    server: 192.168.31.12
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: wireguard-transmission
spec:
  volumeMode: Filesystem
  storageClassName: nfs
  selector:
    matchLabels:
      type: transmission-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti

