apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-downloads-pvc
  namespace: wireguard-transmission
spec:
  volumeMode: Filesystem
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
