# NOTE install smb.csi.k8s.io first !!!
apiVersion: v1
kind: Secret
metadata:
  name: smb-secret
type: Opaque
stringData:
  username: "guest"
  password: ""

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: //192.168.8.1/Realtek_RTL9210B-CG(c4da)/drive
  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  #   csi.storage.k8s.io/provisioner-secret-name: smb-secret
  #   csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: smb-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
reclaimPolicy: Retain  # available values: Delete, Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
